name: Ansible Kubernetes Provisioning


on:

  workflow_run:

    workflows:
      - Terraform Apply

    types:
      - completed

permissions:
  contents: read
  actions: read

jobs:

  ansible:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download generated inventory
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}
          path: .

      - name: Place inventory in Ansible directory
        run: |
          mkdir -p ansible
          cp inventory.ini ansible/inventory.ini

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible
        working-directory: ansible
        run: |
          ansible-playbook \
          -i inventory.ini \
          site.yml